### PR TITLE
:bug: Fixes configuration error with valid configuration

### PR DESCRIPTION
**Pull request by gitvinit**
Fixes AuthenticationClient to pass constructor parameters to BaseOktaClient

Resolves: #12

### CODE REVIEW

**Comment by gitvinit** [comment]
Hi @laura-rodriguez thanks for reviewing the PR I am not sure if tests will add any value its a feature of the c# language https://stackoverflow.com/questions/13166019/will-the-base-class-constructor-be-automatically-called . Please let me know if you want any further clarification on this.

**Comment by laura-rodriguez** [comment]
Hi @gitvinit,

Sorry for the late response and if I wasn't clear enough.
What we want to test here is that the base constructor is called with the correct parameters. 
I believe this test is important so we can ensure we are constructing an `AuthenticationClient` properly and, the issue caused by not calling to the base constructor correctly won't happen again.
Let me know if you have time to do it, otherwise, I will be happy to add the corresponding tests to your branch so we can merge this soon :).

Let me know your thoughts.

**Comment by gitvinit** [comment]
Hi @laura-rodriguez thanks for the clarification I misunderstood your initial comment as to test if the base constructor was being called. Your test requirement makes sense I am not sure if Ill be able to complete it in soon but if you can provide some help it would be appreciated.

**Comment by laura-rodriguez** [comment]
Hi @gitvinit,

Finally, I found the time to review this properly. Sorry for the delay again!
By looking at the code, there is no need to call the `BaseOktaClient` with parameters as the `AuthenticationClient` constructor does all the work that we need. 
What I suggest is to create a parameterless constructor in the `BaseOktaClient` like this:
```
public BaseOktaClient() { }
```
Then, remove all the `base(..)` calls with parameters from the `AuthenticationClient`.
This way we avoid the default base constructor with parameters is called, and the one parameterless be called instead.

Finally, you can add a unit test in the `AuthenticationClientShould` which tests that a new `AuthenticationClient` is constructed with the right configuration:

```
 [Fact]
        public void BeConstructedWithTheCorrectConfiguration()
        {
            var client = new AuthenticationClient(new OktaClientConfiguration
            {
                OktaDomain = "https://foo.oktapreview.com/",
                Token = "abc123notreal"
            });

            client.Configuration.OktaDomain.Should().Be("https://foo.oktapreview.com/");
            client.Configuration.Token.Should().Be("abc123notreal");
        }
```
Let me know your thoughts!

**Comment by gitvinit** [comment]
Hi @laura-rodriguez sorry for the delay and thanks for reviewing the code and I agree with you it would be better to change the base class. I have updated the code as per your comments and also added the test case as per your suggestion. Can you please review the changes and let me know if anything else is required?

**Comment by laura-rodriguez** [comment]
@gitvinit your changes were merged 🎉  Thanks for your contribution ❤️

**Pull request merged**
